### ISSUE TITLE
Upgrade to Vue 2.6.X

### ISSUE THREAD

**Issue by subdavis** [girder/girder_web_components#152]
I'm going to do this today.  I have a new project that wants GWC.  I know it's backward compatible, but might as well get it done.

**Comment by subdavis** [comment]
required by #134

**Comment by subdavis** [comment]
Turns out I already tried and failed to do this back in april #111 

I'm still running into the same problem https://github.com/vuejs/vue-cli/issues/1584, and I'm stuck again.

**Comment by subdavis** [comment]
To clarify, the issue I'm having now is

```
 FAIL  tests/unit/utils/locationHelper.spec.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /home/brandon/github.com/girder_web_components/node_modules/vuetify/lib/util/colors.js:298
    export default Object.freeze({
    ^^^^^^

    SyntaxError: Unexpected token export

       5 |  */
       6 | 
    >  7 | import colors from 'vuetify/lib/util/colors';
         | ^
       8 | 
       9 | export default {
      10 |   theme: {

      at ScriptTransformer._transformAndBuildScript (node_modules/jest-runtime/build/script_transformer.js:403:17)
      at Object.<anonymous> (src/utils/vuetifyConfig.js:7:1)

```

**Comment by subdavis** [comment]
Done in #154
